
  # For modes: STANDARD, STORAGE, DEVELOP, AUTH
  s3-storage:
    image: ${S3_IMAGE}
    container_name: ${S3_CONTAINER_NAME}
    hostname: ${S3_HOSTNAME}
    restart: ${GENERIC_RESTART}
    command:
      - "server"
      - "/data"
      - "--console-address=:${S3_CONSOLE_PORT}"
    healthcheck:
      test: "bash -c 'printf \"GET / HTTP/1.1\n\n\" > /dev/tcp/127.0.0.1/9000; exit $?;'"
      interval: 10s
      retries: 60
      start_period: 20s
      timeout: 10s
    environment:
      MINIO_ROOT_USER: ${S3_USER}
      MINIO_ROOT_PASSWORD: ${S3_PASSWORD}
      # MINIO_BROWSER_REDIRECT_URL: ${S3_CONSOLE_BROWSER_REDIRECT_URL}
    ports:
      - ${S3_EXTERNAL_PORT}:9000
      - ${S3_CONSOLE_EXTERNAL_PORT}:${S3_CONSOLE_PORT}
    volumes:
      - volume_s3:/data
      - ${TIMEZONE_PATH_ON_HOST}:${TIMEZONE_PATH_ON_CONTAINER}:${TIMEZONE_OPTIONS}    # Map the Timezone  of the host to the Timezone of the container
      - ${LOCALTIME_PATH_ON_HOST}:${LOCALTIME_PATH_ON_CONTAINER}:${LOCALTIME_OPTIONS} # Map the Localtime of the host to the Timezone of the container
    networks:
      - adempiere_network
