
  # For modes: STANDARD, AUTH
  adempiere.site:
    image: ${ADEMPIERE_SITE_IMAGE}
    container_name: ${ADEMPIERE_SITE_CONTAINER_NAME}
    hostname: ${ADEMPIERE_SITE_HOSTNAME}
    restart: ${GENERIC_RESTART}
    volumes:
      - ${TIMEZONE_PATH_ON_HOST}:${TIMEZONE_PATH_ON_CONTAINER}:${TIMEZONE_OPTIONS}    # Map the Timezone  of the host to the Timezone of the container
      - ${LOCALTIME_PATH_ON_HOST}:${LOCALTIME_PATH_ON_CONTAINER}:${LOCALTIME_OPTIONS} # Map the Localtime of the host to the Timezone of the container
    environment:
      ZK_HOST: ${ADEMPIERE_SITE_ZK_URL}
      VUE_HOST: ${ADEMPIERE_SITE_VUE_URL}
      SCHEDULER_HOST: ${ADEMPIERE_SITE_SCHEDULER_URL}
    depends_on:
      - adempiere.zk     # Docker Compose Service
    # ports:
    #  - ${ADEMPIERE_SITE_EXTERNAL_PORT}:${ADEMPIERE_SITE_PORT}
    networks:
      - adempiere_network
